#pragma once

#define MANAPIHTTP_JSON_DEBUG {{ VAR_MANAPIHTTP_JSON_DEBUG }}
#define MANAPIHTTP_OPENSSL_DEPENDENCY {{ VAR_MANAPIHTTP_OPENSSL_DEPENDENCY }}
#define MANAPIHTTP_WOLFSSL_DEPENDENCY {{ VAR_MANAPIHTTP_WOLFSSL_DEPENDENCY }}
#define MANAPIHTTP_QUICHE_DEPENDENCY {{ VAR_MANAPIHTTP_QUICHE_DEPENDENCY }}
#define MANAPIHTTP_TQUIC_DEPENDENCY {{ VAR_MANAPIHTTP_TQUIC_DEPENDENCY }}
#define MANAPIHTTP_ZLIB_DEPENDENCY {{ VAR_MANAPIHTTP_ZLIB_DEPENDENCY }}
#define MANAPIHTTP_CURL_DEPENDENCY {{ VAR_MANAPIHTTP_CURL_DEPENDENCY }}
#define MANAPIHTTP_GMP_DEPENDENCY {{ VAR_MANAPIHTTP_GMP_DEPENDENCY }}
#define MANAPIHTTP_MSQUIC_DEPENDENCY {{ VAR_MANAPIHTTP_MSQUIC_DEPENDENCY }}

// WOLFSSL
#define MANAPIHTTP_WOLFSSL_WITH_ALPN {{ VAR_MANAPIHTTP_WOLFSSL_WITH_ALPN }}